### ISSUE TITLE
split community

### ISSUE THREAD

**Issue by dumedco** [impactMarket/impact-market-smart-contracts#127]

**Comment by obernardovieira** [comment]
verified
split here https://explorer.celo.org/alfajores/tx/0xb57ebc4f855b6cc2fdfe1db0f6eca8b4c42f75e27ab9a3a3c4b989cd180b88a7/logs
copy beneficiaries here
0xf5562083f9ef4c6002981f5633827df0ecb9a35de98afddd8fccc498783b15e5
Only misses updating the subgraph
